from __future__ import annotations

import dataclasses
import hashlib

import pytest

from pluto_plus.adaptive_scan import (
    ACK_BYTES,
    CAPS_BYTES,
    FEEDBACK_BYTES,
    SETUP_BYTES,
    TERMINAL_BYTES,
    VISIT_BYTES,
    VISIT_DEADLINE_FORCED,
    AdaptiveScanProtocolError,
    FeedbackResult,
    ScanAck,
    ScanCapabilities,
    ScanFeedback,
    ScanOutcome,
    ScanSetup,
    ScanTarget,
    ScanTerminal,
    ScanVisit,
    TerminalState,
    VisitResult,
    corruptions,
)


def setup() -> ScanSetup:
    return ScanSetup(
        session=0x1122334455667788,
        generation=9,
        seed=10,
        source_rate_hz=15_000_000,
        analog_bandwidth_hz=12_000_000,
        duration_ms=300_000,
        dwell_ms=240,
        transition_budget_ms=10,
        maximum_revisit_ms=3_000,
        feedback_age_ms=1_000,
        application_delay_ms=1_000,
        decay_ms=5_000,
        maximum_boost=3,
        maximum_queue_bytes=200_000_000,
        maximum_queue_age_ms=5_000,
        maximum_queue_visits=50,
        analysis_digest=bytes(range(1, 33)),
        targets=tuple(
            ScanTarget(
                channel=100 + index,
                profile=index * 2,
                frequency_hz=2_400_000_000 + 25_000_000 * index,
                baseline_weight=index + 1,
                profile_crc32=0x10203040 + index,
            )
            for index in range(3)
        ),
    )


def test_setup_matches_c_golden_and_rejects_every_corruption() -> None:
    request = setup()
    packed = request.pack()
    assert len(packed) == SETUP_BYTES
    # Generated by test_spf_scan_protocol from the independently implemented C codec.
    assert hashlib.sha256(packed).hexdigest() == (
        "b48e7c2d4947f134b4d9bf2840a46a58fb26da4cc4b7cf03ef7165c7e3ad0dda"
    )
    assert ScanSetup.unpack(packed) == request
    for changed in corruptions(packed):
        with pytest.raises(AdaptiveScanProtocolError):
            ScanSetup.unpack(changed)


def test_exact_capabilities_round_trip() -> None:
    capabilities = ScanCapabilities()
    packed = capabilities.pack()
    assert len(packed) == CAPS_BYTES
    assert ScanCapabilities.unpack(packed) == capabilities
    for changed in corruptions(packed):
        with pytest.raises(AdaptiveScanProtocolError):
            ScanCapabilities.unpack(changed)


def test_source_bound_records_round_trip_and_reject_corruption() -> None:
    request = setup()
    visit = ScanVisit(
        session=request.session,
        generation=request.generation,
        visit=7,
        selection_counter=0x200000000,
        transition_before=0x200000001,
        transition_after=0x200000101,
        valid_start=0x200000201,
        valid_end=0x200003201,
        frequency_hz=request.targets[1].frequency_hz,
        iq_bytes=0x3000 * 4,
        missing_samples_before=0,
        analog_bandwidth_hz=request.analog_bandwidth_hz,
        source_rate_hz=request.source_rate_hz,
        target=1,
        profile=request.targets[1].profile,
        result=VisitResult.COMPLETE,
        eligible_mask=7,
        effective_weight=65536 * 2,
        profile_crc32=request.targets[1].profile_crc32,
        flags=1 | VISIT_DEADLINE_FORCED,
    )
    feedback = ScanFeedback(
        session=request.session,
        generation=request.generation,
        sequence=11,
        visit=visit.visit,
        valid_start=visit.valid_start,
        valid_end=visit.valid_end,
        target=visit.target,
        outcome=ScanOutcome.ACTIVE,
        analysis_digest=request.analysis_digest,
    )
    ack = ScanAck(
        sequence=feedback.sequence,
        source_visit=visit.visit,
        first_visit=8,
        received_counter=visit.valid_end + 1,
        application_counter=visit.valid_end + 2,
        target=visit.target,
        result=FeedbackResult.APPLIED,
        old_boost=1,
        new_boost=3,
    )
    terminal = ScanTerminal(
        session=request.session,
        generation=request.generation,
        final_counter=0x300000000,
        restore_before=0x300000001,
        restore_after=0x300000101,
        planned=10,
        delivered=8,
        skipped=1,
        invalid=1,
        cancelled=0,
        iq_bytes=123456,
        state=TerminalState.COMPLETED,
        reason=1,
        error=0,
    )
    records = (
        (visit, ScanVisit, VISIT_BYTES),
        (feedback, ScanFeedback, FEEDBACK_BYTES),
        (ack, ScanAck, ACK_BYTES),
        (terminal, ScanTerminal, TERMINAL_BYTES),
    )
    for model, decoder, size in records:
        packed = model.pack()
        assert len(packed) == size
        assert decoder.unpack(packed) == model
        for changed in corruptions(packed):
            with pytest.raises(AdaptiveScanProtocolError):
                decoder.unpack(changed)


def test_setup_rejects_duplicate_profiles_and_unsupported_rate() -> None:
    request = setup()
    duplicate_profile = dataclasses.replace(
        request.targets[1], profile=request.targets[0].profile
    )
    with pytest.raises(AdaptiveScanProtocolError, match="profiles"):
        dataclasses.replace(request, targets=(request.targets[0], duplicate_profile)).pack()
    with pytest.raises(AdaptiveScanProtocolError, match="10/15/20/30"):
        dataclasses.replace(request, source_rate_hz=60_000_000).pack()
